channels:
- conda-forge
dependencies:
- python=3.10.8
- pip<=23.2.1
- pip:
  - mlflow==2.4
  - azureml-mlflow==1.53.0
  - cloudpickle==2.2.1
  - numpy==1.23.5
  - psutil==5.9.5
  - scikit-learn==1.3.0
  - scipy==1.10.1
  - pandas==1.3.4
name: sklearn-clf-env